language: cpp
sudo: false
env: 
  global:
    - OPENBLAS_NUM_THREADS=1
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      env: 
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - liblapack-dev
            - libopenblas-dev
            - fftw3-dev

before_install:
    - eval "${MATRIX_EVAL}"

install:
    - gcc --version
    - cd ./bin/
    - make
notifications:
    email: false
